CATALOGUE_HOST: catalogue.backend-{{ env }}.devaws46.online
USER_HOST: user.backend-{{ env }}.devaws46.online 
CART_HOST: cart.backend-{{ env }}.devaws46.online
SHIPPING_HOST: shipping.backend-{{ env }}.devaws46.online
PAYMENT_HOST: payment.backend-{{ env }}.devaws46.online