CATALOGUE_HOST: catalogue.backened-{{ env }}.devaws46.online
USER_HOST: user.backened-{{ env }}.devaws46.online 
CART_HOST: cart.backened-{{ env }}.devaws46.online
SHIPPING_HOST: shipping.backened-{{ env }}.devaws46.online
PAYMENT_HOST: payment.backened-{{ env }}.devaws46.online